-- Project Genesis: is everything from supabase/migrations in this database?
-- Generated by Tools/Supabase/make_verify_sql.py; read-only, safe to run any time.
-- SQL Editor -> New query -> paste -> Run. Anything MISSING: run that migration.

with expected (migration, kind, name) as (
  values
    ('20260929000000_phase2_sync.sql', 'table', 'bookmarks'),
    ('20260929000000_phase2_sync.sql', 'table', 'highlight_collections'),
    ('20260929000000_phase2_sync.sql', 'table', 'highlights'),
    ('20260929000000_phase2_sync.sql', 'table', 'notes'),
    ('20260929000000_phase2_sync.sql', 'table', 'reading_plans'),
    ('20260929000000_phase2_sync.sql', 'table', 'prayers'),
    ('20260929000000_phase2_sync.sql', 'rls', 'bookmarks'),
    ('20260929000000_phase2_sync.sql', 'rls', 'highlight_collections'),
    ('20260929000000_phase2_sync.sql', 'rls', 'highlights'),
    ('20260929000000_phase2_sync.sql', 'rls', 'notes'),
    ('20260929000000_phase2_sync.sql', 'rls', 'reading_plans'),
    ('20260929000000_phase2_sync.sql', 'rls', 'prayers'),
    ('20260929000000_phase2_sync.sql', 'function', 'genesis_touch_server_updated_at'),
    ('20260930000000_phase3_study_ai.sql', 'table', 'ai_cache'),
    ('20260930000000_phase3_study_ai.sql', 'table', 'ai_usage'),
    ('20260930000000_phase3_study_ai.sql', 'table', 'premium_entitlements'),
    ('20260930000000_phase3_study_ai.sql', 'rls', 'ai_cache'),
    ('20260930000000_phase3_study_ai.sql', 'rls', 'ai_usage'),
    ('20260930000000_phase3_study_ai.sql', 'rls', 'premium_entitlements'),
    ('20260930000000_phase3_study_ai.sql', 'function', 'reserve_ai_usage'),
    ('20260930000000_phase3_study_ai.sql', 'function', 'release_ai_usage'),
    ('20261001000000_feature_flags.sql', 'table', 'feature_flags'),
    ('20261001000000_feature_flags.sql', 'rls', 'feature_flags'),
    ('20261002000000_audio_recordings.sql', 'table', 'audio_recordings'),
    ('20261002000000_audio_recordings.sql', 'rls', 'audio_recordings'),
    ('20261003000000_groups_community.sql', 'table', 'profiles'),
    ('20261003000000_groups_community.sql', 'table', 'blocked_terms'),
    ('20261003000000_groups_community.sql', 'table', 'community_bans'),
    ('20261003000000_groups_community.sql', 'table', 'user_blocks'),
    ('20261003000000_groups_community.sql', 'table', 'content_reports'),
    ('20261003000000_groups_community.sql', 'table', 'groups'),
    ('20261003000000_groups_community.sql', 'table', 'group_members'),
    ('20261003000000_groups_community.sql', 'table', 'group_progress'),
    ('20261003000000_groups_community.sql', 'table', 'group_prayers'),
    ('20261003000000_groups_community.sql', 'table', 'group_prayer_marks'),
    ('20261003000000_groups_community.sql', 'table', 'group_posts'),
    ('20261003000000_groups_community.sql', 'table', 'group_announcements'),
    ('20261003000000_groups_community.sql', 'table', 'community_posts'),
    ('20261003000000_groups_community.sql', 'table', 'community_comments'),
    ('20261003000000_groups_community.sql', 'table', 'community_reactions'),
    ('20261003000000_groups_community.sql', 'table', 'push_tokens'),
    ('20261003000000_groups_community.sql', 'rls', 'profiles'),
    ('20261003000000_groups_community.sql', 'rls', 'blocked_terms'),
    ('20261003000000_groups_community.sql', 'rls', 'community_bans'),
    ('20261003000000_groups_community.sql', 'rls', 'user_blocks'),
    ('20261003000000_groups_community.sql', 'rls', 'content_reports'),
    ('20261003000000_groups_community.sql', 'rls', 'groups'),
    ('20261003000000_groups_community.sql', 'rls', 'group_members'),
    ('20261003000000_groups_community.sql', 'rls', 'group_progress'),
    ('20261003000000_groups_community.sql', 'rls', 'group_prayers'),
    ('20261003000000_groups_community.sql', 'rls', 'group_prayer_marks'),
    ('20261003000000_groups_community.sql', 'rls', 'group_posts'),
    ('20261003000000_groups_community.sql', 'rls', 'group_announcements'),
    ('20261003000000_groups_community.sql', 'rls', 'community_posts'),
    ('20261003000000_groups_community.sql', 'rls', 'community_comments'),
    ('20261003000000_groups_community.sql', 'rls', 'community_reactions'),
    ('20261003000000_groups_community.sql', 'rls', 'push_tokens'),
    ('20261003000000_groups_community.sql', 'column', 'group_members.notifications'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_feature_on'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_is_member'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_is_leader'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_prayer_group'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_is_objectionable'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_can_post_community'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_prepare_content'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_count_reactions'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_after_report'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_stamp_row'),
    ('20261003000000_groups_community.sql', 'function', 'set_display_name'),
    ('20261003000000_groups_community.sql', 'function', 'accept_community_terms'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_check_group'),
    ('20261003000000_groups_community.sql', 'function', 'genesis_new_invite_code'),
    ('20261003000000_groups_community.sql', 'function', 'create_group'),
    ('20261003000000_groups_community.sql', 'function', 'join_group'),
    ('20261003000000_groups_community.sql', 'function', 'update_group'),
    ('20261003000000_groups_community.sql', 'function', 'new_invite_code'),
    ('20261003000000_groups_community.sql', 'function', 'set_member_role'),
    ('20261003000000_groups_community.sql', 'function', 'remove_member'),
    ('20261003000000_groups_community.sql', 'function', 'leave_group'),
    ('20261003000000_groups_community.sql', 'function', 'delete_group'),
    ('20261003000000_groups_community.sql', 'function', 'remove_content'),
    ('20261003000000_groups_community.sql', 'function', 'set_group_notifications'),
    ('20261003000000_groups_community.sql', 'function', 'set_prayer_answered'),
    ('20261003000000_groups_community.sql', 'function', 'community_feed'),
    ('20261003000000_groups_community.sql', 'function', 'block_post_author'),
    ('20261004000000_bible_translations.sql', 'table', 'bible_translations'),
    ('20261004000000_bible_translations.sql', 'rls', 'bible_translations'),
    ('20261004000000_bible_translations.sql', 'bucket', 'bibles'),
    ('20261006000000_memory_verses.sql', 'table', 'memory_verses'),
    ('20261006000000_memory_verses.sql', 'rls', 'memory_verses'),
    ('20261007000000_feedback_and_grants.sql', 'table', 'app_feedback'),
    ('20261007000000_feedback_and_grants.sql', 'table', 'premium_grants'),
    ('20261007000000_feedback_and_grants.sql', 'rls', 'app_feedback'),
    ('20261007000000_feedback_and_grants.sql', 'rls', 'premium_grants'),
    ('20261008000000_group_progress_summary.sql', 'function', 'group_progress_summary')
),
checked as (
  select e.migration, e.kind, e.name,
    case e.kind
      when 'table' then to_regclass('public.' || e.name) is not null
      when 'rls' then coalesce((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = 'public' and c.relname = e.name), false)
      when 'column' then exists (select 1 from information_schema.columns
                                 where table_schema = 'public' and table_name = split_part(e.name, '.', 1)
                                   and column_name = split_part(e.name, '.', 2))
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                   where n.nspname = 'public' and p.proname = e.name)
      when 'bucket' then exists (select 1 from storage.buckets b where b.id = e.name)
    end as present
  from expected e
)
select migration, kind, name, case when present then 'OK' else 'MISSING' end as status
from checked
order by present, migration, kind, name;
