#!/usr/bin/env python3
"""Builds a downloadable translation and the Supabase row that lists it.

Translations beyond the three bundled ones are downloaded in the app
(Library › Bibles). Each is the same SQLite format as the bundled Bibles,
compressed with raw DEFLATE (which iOS reads with NSData.decompressed(using:
.zlib)), and listed in public.bible_translations with its size and SHA-256 so
the app can check the file.

Example: the Berean Standard Bible (public domain since April 30, 2023).

  git clone --depth 1 --filter=blob:none --sparse https://github.com/scrollmapper/bible_databases /tmp/sm
  (cd /tmp/sm && git sparse-checkout set --no-cone /formats/json/BSB.json)
  python3 Tools/BibleData/package_translation.py --scrollmapper /tmp/sm --id BSB \\
      --summary "A modern, accurate translation in clear, readable English." \\
      --url https://ulbpwygzwchsnvdeeife.supabase.co/storage/v1/object/public/bibles/BSB-1.sqlite.deflate \\
      --out build/bibles

The Reina-Valera 1909 (Spanish, public domain) the same way, with
--id RV1909 and formats/json/SpaRV.json checked out.

Then upload build/bibles/BSB-1.sqlite.deflate to the public "bibles" bucket in
Supabase Storage and run build/bibles/BSB-1.sql in the SQL Editor (see
PHASE4_SETUP.md). To publish a corrected edition, bump --version: the app
updates downloaded copies automatically.
"""
import argparse
import hashlib
import os
import sqlite3
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_bibles import TRANSLATIONS, create_bible_db, load_scrollmapper  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LAYOUT_SOURCE = os.path.join(ROOT, "Genesis", "Resources", "Bibles", "WEB.sqlite")


def sql_text(value):
    return "null" if value is None else "'" + str(value).replace("'", "''") + "'"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scrollmapper", required=True, help="checkout of scrollmapper/bible_databases")
    parser.add_argument("--id", required=True, choices=sorted(TRANSLATIONS))
    parser.add_argument("--summary", required=True)
    parser.add_argument("--url", required=True, help="public https URL the compressed file will have")
    parser.add_argument("--version", type=int, default=1)
    parser.add_argument("--sort", type=int, default=10)
    parser.add_argument("--out", default="build/bibles")
    args = parser.parse_args()
    if not args.url.startswith("https://"):
        sys.exit("--url must be https")

    os.makedirs(args.out, exist_ok=True)
    verses, headings = load_scrollmapper(args.scrollmapper, args.id)
    # Paragraphs and poetry come from the WEB, as for the bundled KJV and ASV
    # (layout only; the words are the translation's own).
    layout = {}
    with sqlite3.connect(LAYOUT_SOURCE) as web:
        for vid, paragraph, poetry in web.execute("SELECT id, paragraph, poetry FROM verses"):
            layout[vid] = (bool(paragraph), bool(poetry))
    for v in verses:
        key = v.book * 1_000_000 + v.chapter * 1_000 + v.verse
        v.paragraph, v.poetry = layout.get(key, (v.verse == 1, False))

    name = f"{args.id}-{args.version}"
    database = os.path.join(args.out, f"{name}.sqlite")
    create_bible_db(database, args.id, verses, headings)
    raw = open(database, "rb").read()
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)  # raw DEFLATE, no header
    packed = compressor.compress(raw) + compressor.flush()
    packed_path = database + ".deflate"
    open(packed_path, "wb").write(packed)
    assert zlib.decompress(packed, -15) == raw

    meta = TRANSLATIONS[args.id]
    statement = (
        "-- Generated by Tools/BibleData/package_translation.py. Upload the .deflate file first, then run this.\n"
        "insert into public.bible_translations (id, name, year, license, summary, language, file_url, file_bytes, database_bytes, sha256, version, enabled, sort, updated_at)\n"
        f"values ({sql_text(args.id)}, {sql_text(meta['name'])}, {sql_text(meta['year'])}, {sql_text(meta['license'])}, {sql_text(args.summary)}, {sql_text(meta['language'])}, "
        f"{sql_text(args.url)}, {len(packed)}, {len(raw)}, {sql_text(hashlib.sha256(raw).hexdigest())}, {args.version}, true, {args.sort}, now())\n"
        "on conflict (id) do update set name = excluded.name, year = excluded.year, license = excluded.license, summary = excluded.summary, language = excluded.language,\n"
        "  file_url = excluded.file_url, file_bytes = excluded.file_bytes, database_bytes = excluded.database_bytes, sha256 = excluded.sha256,\n"
        "  version = excluded.version, enabled = excluded.enabled, sort = excluded.sort, updated_at = now();\n"
    )
    open(os.path.join(args.out, f"{name}.sql"), "w").write(statement)
    print(f"{args.id}: {len(verses)} verses; {len(raw) / 1e6:.1f} MB, {len(packed) / 1e6:.1f} MB compressed")
    print(f"Wrote {packed_path} and {os.path.join(args.out, name + '.sql')}")


if __name__ == "__main__":
    main()
