// Generated by Tools/BibleData/align_versification.py. Don't edit by hand.

extension OriginalVersification {
    /// Reina-Valera 1909 verses numbered differently from the KJV (open-bibles'
    /// USFX keeps the Spanish numbering): which KJV verses each one holds.
    /// Every other verse has the KJV's number.
    static let reinaValera1909Exceptions: [VerseAlignment] = reinaValera1909Rules.flatMap { $0 }

    private static let reinaValera1909Rules: [[VerseAlignment]] = [
        shift(book: 4, chapter: 13, verses: 1...1, kjvChapter: 12, by: 15),
        shift(book: 4, chapter: 13, verses: 2...32, kjvChapter: 13, by: -1),
        group(book: 4, [(13, 33)], kjv: [(13, 32), (13, 33)]),
        shift(book: 4, chapter: 30, verses: 1...1, kjvChapter: 29, by: 39),
        shift(book: 4, chapter: 30, verses: 2...15, kjvChapter: 30, by: -1),
        group(book: 4, [(30, 16)], kjv: [(30, 15), (30, 16)]),
        group(book: 7, [(14, 18), (14, 19)], kjv: [(14, 18)]),
        group(book: 7, [(14, 20)], kjv: [(14, 19), (14, 20)]),
        group(book: 9, [(10, 25), (10, 26)], kjv: [(10, 25), (10, 26)]),
        group(book: 9, [(19, 1), (19, 2)], kjv: [(19, 1), (19, 2)]),
        shift(book: 9, chapter: 24, verses: 1...1, kjvChapter: 23, by: 28),
        shift(book: 9, chapter: 24, verses: 2...21, kjvChapter: 24, by: -1),
        group(book: 9, [(24, 22)], kjv: [(24, 21), (24, 22)]),
        group(book: 10, [(2, 31), (2, 32)], kjv: [(2, 31), (2, 32)]),
        group(book: 10, [(20, 25)], kjv: [(20, 25), (20, 26)]),
        group(book: 11, [(16, 29), (16, 30)], kjv: [(16, 29), (16, 30)]),
        group(book: 11, [(18, 33), (18, 34)], kjv: [(18, 33), (18, 34)]),
        group(book: 11, [(22, 43), (22, 44)], kjv: [(22, 43)]),
        shift(book: 11, chapter: 22, verses: 45...52, kjvChapter: 22, by: -1),
        group(book: 11, [(22, 53)], kjv: [(22, 52), (22, 53)]),
        group(book: 12, [(4, 30), (4, 31)], kjv: [(4, 30), (4, 31)]),
        group(book: 13, [(1, 30)], kjv: [(1, 30), (1, 31)]),
        group(book: 13, [(1, 31), (1, 32)], kjv: [(1, 32)]),
        group(book: 13, [(2, 34), (2, 35)], kjv: [(2, 34), (2, 35)]),
        group(book: 13, [(21, 15), (21, 16)], kjv: [(21, 15)]),
        shift(book: 13, chapter: 21, verses: 17...29, kjvChapter: 21, by: -1),
        group(book: 13, [(21, 30)], kjv: [(21, 29), (21, 30)]),
        group(book: 14, [(33, 10)], kjv: [(33, 10), (33, 11)]),
        shift(book: 14, chapter: 33, verses: 11...24, kjvChapter: 33, by: 1),
        group(book: 18, [(35, 15)], kjv: [(35, 15), (35, 16)]),
        shift(book: 18, chapter: 39, verses: 1...3, kjvChapter: 38, by: 38),
        shift(book: 18, chapter: 39, verses: 4...29, kjvChapter: 39, by: -3),
        group(book: 18, [(39, 30)], kjv: [(39, 27), (39, 28), (39, 29), (39, 30), (40, 1), (40, 2), (40, 3), (40, 4), (40, 5)]),
        shift(book: 18, chapter: 40, verses: 1...19, kjvChapter: 40, by: 5),
        shift(book: 28, chapter: 12, verses: 1...1, kjvChapter: 11, by: 11),
        shift(book: 28, chapter: 12, verses: 2...13, kjvChapter: 12, by: -1),
        group(book: 28, [(12, 14)], kjv: [(12, 13), (12, 14)]),
        shift(book: 32, chapter: 2, verses: 1...1, kjvChapter: 1, by: 16),
        shift(book: 32, chapter: 2, verses: 2...9, kjvChapter: 2, by: -1),
        group(book: 32, [(2, 10)], kjv: [(2, 9), (2, 10)]),
        group(book: 42, [(7, 18), (7, 19)], kjv: [(7, 18), (7, 19)]),
        group(book: 44, [(19, 40)], kjv: [(19, 40), (19, 41)]),
        group(book: 47, [(13, 12)], kjv: [(13, 12), (13, 13)]),
        shift(book: 47, chapter: 13, verses: 13...13, kjvChapter: 13, by: 1),
    ]
}
