#!/usr/bin/env python3
"""Writes supabase/verify_setup.sql: one query that checks every table,
column, function, row-level-security switch and storage bucket the
migrations create, and lists anything missing by migration file.

    python3 Tools/Supabase/make_verify_sql.py

Run the generated file in the Supabase SQL Editor. Every row says OK or
MISSING; re-run the migration named on a MISSING row.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS = ROOT / "supabase" / "migrations"
OUT = ROOT / "supabase" / "verify_setup.sql"

checks: list[tuple[str, str, str]] = []  # (migration, kind, name)
for path in sorted(MIGRATIONS.glob("*.sql")):
    sql = path.read_text()
    name = path.name
    for table in re.findall(r"create table if not exists public\.([a-z_]+)", sql):
        checks.append((name, "table", table))
    for table in re.findall(r"alter table public\.([a-z_]+) enable row level security", sql):
        checks.append((name, "rls", table))
    for table, column in re.findall(r"alter table public\.([a-z_]+) add column if not exists ([a-z_]+)", sql):
        checks.append((name, "column", f"{table}.{column}"))
    for function in re.findall(r"create or replace function public\.([a-z_]+)", sql):
        checks.append((name, "function", function))
    for bucket in re.findall(r"insert into storage\.buckets[^;]*?values\s*\(\s*'([a-z0-9_-]+)'", sql, re.S):
        checks.append((name, "bucket", bucket))

seen = set()
unique = []
for check in checks:
    if check[1:] not in seen:
        seen.add(check[1:])
        unique.append(check)

values = ",\n    ".join(f"('{m}', '{k}', '{n}')" for m, k, n in unique)
OUT.write_text(f"""-- Project Genesis: is everything from supabase/migrations in this database?
-- Generated by Tools/Supabase/make_verify_sql.py; read-only, safe to run any time.
-- SQL Editor -> New query -> paste -> Run. Anything MISSING: run that migration.

with expected (migration, kind, name) as (
  values
    {values}
),
checked as (
  select e.migration, e.kind, e.name,
    case e.kind
      when 'table' then to_regclass('public.' || e.name) is not null
      when 'rls' then coalesce((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = 'public' and c.relname = e.name), false)
      when 'column' then exists (select 1 from information_schema.columns
                                 where table_schema = 'public' and table_name = split_part(e.name, '.', 1)
                                   and column_name = split_part(e.name, '.', 2))
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                   where n.nspname = 'public' and p.proname = e.name)
      when 'bucket' then exists (select 1 from storage.buckets b where b.id = e.name)
    end as present
  from expected e
)
select migration, kind, name, case when present then 'OK' else 'MISSING' end as status
from checked
order by present, migration, kind, name;
""")
print(f"{OUT.relative_to(ROOT)}: {len(unique)} checks")
